language: "ko-KR"

reviews:
  profile: "chill" # 코드리뷰 강도 chill or assertive
  request_changes_workflow: true # CodeRabbit 리뷰 후 PR Approve 진행
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  poem: false
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: "src/test/java/**/*.java"
      instructions: |
        테스트 코드 네이밍 규칙:
        - 테스트 메서드명은 한글과 _를 조합한 형태를 따릅니다.
chat:
  auto_reply: true
