server:
  port: 8080

dev-host: https://hosting-not-yet

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  mail:
    #    host: smtp.naver.com
    host: smtp.${HOST_ADDRESS}
    port: 465
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    address: ${MAIL_ADDRESS}@${HOST_ADDRESS}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  access-secret-key: ${ACCESS_SECRET_KEY}
  refresh-secret-key: ${REFRESH_SECRET_KEY}
  access-token-valid: 1814400
  refresh-token-valid: 1814400

cookie:
  name: BP_RT

---
server:
  port: 8080

dev-host: https://hosting-not-yet

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:true

  mail:
    #    host: smtp.naver.com
    host: smtp.${HOST_ADDRESS}
    port: 465
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  access-secret-key: ${ACCESS_SECRET_KEY}
  refresh-secret-key: ${REFRESH_SECRET_KEY}
  access-token-valid: 1814400
  refresh-token-valid: 1814400

cookie:
  name: BP_RT

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:true

  mail:
    #    host: smtp.naver.com
    host: smtp.test.com
    port: 465
    username: test
    password: test
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  access-secret-key: accessabcdefghijklmnopqrstuvwxyz
  refresh-secret-key: refreshabcdefghijklmnopqrstuvwxyz
  access-token-valid: 1814400
  refresh-token-valid: 1814400

cookie:
  name: BP_RT
