name: CD API DOCS

on:
  push:
    branches: [ "develop", "main" ]

permissions: write-all

jobs:
  update-api-docs-server:
    name: 📑 Swagger 문서 자동 배포
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 가져오기
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 패키지 캐싱
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle 명령어 권한을 부여
        run: chmod +x gradlew

      - name: OpenAPI 스펙 생성
        run: ./gradlew test --tests "*ControllerTest" -Dspring.profiles.active=dev

      - name: API 문서 서버 레포 체크아웃
        uses: actions/checkout@v4
        with:
          repository: fprh13/boilerplate-api-docs-server
          token: ${{ secrets.BP_DOCS_REPO_TOKEN }}
          path: api-docs-repo

      - name: API 문서 결과물 복사
        run: cp build/api-spec/openapi3.yaml api-docs-repo/openapi3.yaml

      - name: API 문서 서버 레포에 반영
        run: |
          cd api-docs-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add openapi3.yaml
          git commit -m "chore: API 문서 최신화" || echo "추가된 API 문서 작업이 없습니다."
          git push
